name: Format

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2

      - name: Setup Node.js environment ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install
      - run: pnpm run format

			- name: Add, Commit and Push
			  uses: EndBug/add-and-commit@v9
        with:
          message: "Format"
          default_author: github_actions