name: Format

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.11

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: pnpm install

      - name: Format
        run: pnpm run format

      - name: Add, Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Format"
          default_author: github_actions
