name: Release Chrome Extension

on: [workflow_dispatch]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --ignore-scripts

      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.sha }}
          restore-keys: |
            turbo-

      - name: Build
        run: pnpm build
        env:
          CI: true

      - name: Upload & release Extension
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: packages/extension/dist/chrome.zip
          extension-id: kmcfjchnmmaeeagadbhoofajiopoceel
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
