name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        node-version: [16.x, 17.x]
        operating-system: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.2.1

      - name: Setup Node.js environment ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install
        env:
          CI: true

      - run: pnpm run build
        env:
          CI: true

      - run: pnpm run test
        env:
          CI: true

      - run: pnpm run typecheck
        env:
          CI: true
